### ISSUE TITLE
"I guess this. . ."?

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-homepage-demo#2]
I realize this comes from our examples so we probably need to revisit in [ml5-examples](https://github.com/ml5js/ml5-examples), but I wonder if the "I guess this..." language is problematic / misleading. I like the friendly, informal nature of it but who is I referring to exactly? 

![screen shot 2018-06-06 at 9 48 22 pm](https://user-images.githubusercontent.com/191758/41073901-6c3a70bc-69d3-11e8-8a90-156eabe59cba.png)

I'll tag @stephkoltun here since she has been doing such wonderful work copy editing for us!

**Comment by shiffman** [comment]
Some options:

> robin, American robin, Turdus migratorius, confidence: 99.11%.

> MobileNet classified this as a robin, American robin, Turdus migratorius with a confidence of 99.11%.

> The model's guess is a robin, American robin, Turdus migratorius with a confidence of 99.11%.

I think maybe the last one?

**Comment by yining1023** [comment]
The last one sounds good.
Or combine the two?
> The MobileNet model's guess is a robin, American robin, Turdus migratorius
> with a confidence of 99.11%.

**Comment by stephkoltun** [comment]
Yeah I agree with Yining — a combination of the two. Something like

> The MobileNet model classified (or labelled?) this as a robin, American robin, Turdus migratorius
with a confidence of 99.11%.

**Comment by yining1023** [comment]
Sounds good! I put 
> The MobileNet model labeled this as a robin
> with a confidence of 99.11%.

Please feel free to edit it.

**Comment by cvalenzuela** [comment]
This seems resolved! https://github.com/ml5js/ml5-examples/issues/27 is still open
